#!/bin/bash

LC_ALL=C

# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

function __run() #(step, name, cmd)
{
    local output exit_code

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"

    output=$(eval "$3" 2>&1)
    exit_code=$?

    if [[ 0 == $exit_code || 130 == $exit_code ]]; then
        echo -e "${C_GREEN}✔${C_RESET}"
    else
        echo -e "${C_RED}🤬${C_RESET}\n\n$output"
        exit 1
    fi
}

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
__run "1/3" "run-phpstan" "make run-phpstan"
__run "2/3" "run-phpcs" "make run-phpcs"
__run "3/3" "run-tests" "make run-tests"
elif [[ "$OSTYPE" == "darwin"* ]]; then
__run "1/3" "run-phpstan" "./vendor/bin/phpstan analyse -c ./phpstan.neon"
__run "2/3" "run-phpcs" "./vendor/bin/phpcs --colors --standard=./phpcs_rulset.xml -p"
__run "3/3" "run-tests" "./vendor/bin/phpunit"
fi
